[package]
name = "universal-config"
version = "0.1.1"
edition = "2021"
description = "A library to simplify reading configuration files from various file formats."
license = "MIT"
keywords = ["config", "serde"]

[features]
default = ["json", "yaml", "toml", "corn", "xml"]

# aliases
# toml does not need to be explicitly included as the dep provides a feature
json = ["serde_json"]
yaml = ["serde_yaml"]
corn = ["libcorn"]
xml = ["serde-xml-rs"]

[dependencies]
serde = "1.0.155"
dirs = "4.0.0"
thiserror = "1.0.39"
tracing = "0.1.37"

# optional
serde_json = { version = "1.0.94", optional = true }
serde_yaml = { version = "0.9.19", optional = true }
toml = { version = "0.7.2", optional = true }
libcorn = { version = "0.6.1", optional = true }
serde-xml-rs = { version = "0.6.0", optional = true }